{% set name = "xeus-sqlite" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-sqlite/archive/{{ version }}.tar.gz
  sha256: ac59dfd173a3a364f6bbb4645aba93d34faf8347b01590542deecacfbc998773

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - xeus >=0.23.2,<0.25
    - cppzmq
    - zeromq
    - nlohmann_json
    - xtl
    - cpp-tabulate >=1.3,<2
    - sqlitecpp
    - sqlite
    - xvega >=0.0.4
    - xvega-bindings >=0.0.3
    - xproperty

test:
  commands:
    - test -f ${PREFIX}/bin/xsqlite  # [unix]
    - if exist %LIBRARY_PREFIX%\bin\xsqlite.exe (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/jupyter-xeus/xeus-sqlite
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter kernel for SQLite based on xeus
  doc_url: https://xeus-sqlite.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
    - jtpio
    - marimeireles
