{% set name = "xeus-sqlite" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-sqlite/archive/{{ version }}.tar.gz
  sha256: afe48c1808e8268dcfbdffc3b6deacbd8ac1d16ca23e3c0c7680371b61a295ba

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make  # [unix]
  host:
    - xeus-zmq >=3.0.0,<4.0.0
    - nlohmann_json
    - xtl
    # cpp-tabulate 1.5 is backward incompatible
    - cpp-tabulate >=1.5
    - sqlitecpp
    - sqlite
    - xvega >=0.1.0
    - xvega-bindings >=0.1.0
    - xproperty >=0.12.0
  run:
    - xvega >=0.0.10
    - xvega-bindings >=0.0.10

test:
  commands:
    - test -f ${PREFIX}/bin/xsqlite  # [unix]
    - if exist %LIBRARY_PREFIX%\bin\xsqlite.exe (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/jupyter-xeus/xeus-sqlite
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter kernel for SQLite based on xeus
  doc_url: https://xeus-sqlite.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
    - jtpio
    - marimeireles
